### ISSUE TITLE
correct output wrong item

### ISSUE THREAD

**Issue by DiggityMan420** [benbenlaw/opolisutilities#2]
so I'm playing stoneopolis great BTW and I came across the need for water in the latex part so I placed a fluid gen and waterlogged leaves on top (see pic) which does produce water (wish I could do this with lava) but the output chat says making jungle leaves (that's what is water logged up there) i know its just looking at the block above it but didnt know if you knew this was possible or not and wanted to fix it
![ss1](https://github.com/bbl-team/Opolis-Utilities/assets/45196448/54bb6807-3785-4c4c-a377-03e4f5f21564)

**Comment by benbenlaw** [comment]
fixed in latest dev version

**Comment by DiggityMan420** [comment]
sweet got it loive the added pic on the front of the strainer too makes it easy to know what in it
