### ISSUE TITLE
Ender scrambler doesn't seem to affect damaged endermen

### ISSUE THREAD

**Issue by usernamepassword123** [benbenlaw/opolisutilities#4]
Title explains the issue, but in the Seaopolis: Submerged modpack, I tried making an enderman farm using a summoning block and ender scramblers.

The endermen would fall into the chamber that left them at half a heart, but a good amount would teleport away after taking damage, around 5-10% from what I have seen.

**Comment by benbenlaw** [comment]
that seems really strange are you sure the block is in range of the enderman

**Comment by usernamepassword123** [comment]
I am pretty sure, I'll add a photo of how I have my setup done.

**Comment by usernamepassword123** [comment]
Here are some photos showing my setup off and where the endermen teleport, they either teleport once they hit the hoppers or don't teleport at all.
![2024-07-16_10 23 45](https://github.com/user-attachments/assets/ada49d49-4dfa-4098-8655-0db49cb07bd9)
![2024-07-16_10 23 49](https://github.com/user-attachments/assets/2cdd8911-d0ce-4bac-9734-4c31d4333fe4)
![2024-07-16_10 26 45](https://github.com/user-attachments/assets/2734133c-88cd-4c02-9b5c-39bd9dee23db)

**Comment by usernamepassword123** [comment]
Alright, I got a video of the ender scrambler just not working in general. Skip to like 42 seconds, I can't edit videos

https://github.com/user-attachments/assets/8a372e8d-8181-4b2b-8ce6-24721e03f3b8

**Comment by benbenlaw** [comment]
maybe fixed
